#!/bin/bash
sudo apt update && sudo apt install git -y
cd /opt
sudo git clone "https://github.com/NataliyaKh/shvirtd-example-python"
cd shvirtd-example-python
sudo chmod 666 /var/run/docker.sock
docker compose up -d
