include:
  - proxy.yaml

services:
  db:
    image: mysql:8
    restart: always
    networks:
        backend:
          ipv4_address: 172.20.0.10
    ports:
    - "127.0.0.1:3306:3306"
    expose:
      - "3306"
    env_file: ".env"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 6s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_TABLE=requests
      - DB_HOST=db
    networks:
      backend:
        ipv4_address: 172.20.0.5

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
